# -*- coding: utf-8 -*-
"""rehex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YbDcdwLTpA_mFx29FVoptZCNT0zhRR-u
"""

https?://(?:\w)(?:.[a-z]+)+(?:/[a-zA-Z0-9.?=&%;-_])*
